### PR TITLE
WIP: Fix Doc Map Type in wls logging exporter jenkins-ignore

### PR DESCRIPTION
**Pull request by hzhao-github**
Changed Doc Map Type from "_doc" to "doc" in wls logging exporter

### CODE REVIEW

**Comment by hzhao-github** [comment]
Here are steps to test it:
------------------------------
1.  Downloaded snakeyaml-1.23.jar
2.  Cloned weblogic-logging-exporter source code from this location
3.  Build weblogic-logging-exporter-0.1.jar
4.  Created WebLogicLoggingExporter.yaml
5.  Configed domain and startup class offline
6.  Created and started WLS domain
7.  Copied weblogic-logging-exporter-0.1.jar and snakeyaml-1.23.jar to $DOMAIN_HOME/lib/ and WebLogicLoggingExporter.yaml to $DOMAIN_HOME/config in WLS managed server pods
8.  Restarted all managed server pods
9.  to Verify:
     1) check the index name "wls" exists in the server pods
     2) Issue some Elasticsearch RESTful API calls to make sure wls logs are pushed to Elasticsearch repository
     3) Launch Kibana Console, verify that index name "wls" and WLS logs are showing up

And four scenarios were tested:
----------------------------------
1.	ELK Stack 5.6.16 + Exporter doc type = “_doc”
Test failed. No WLS logs pushed to Elasticsearch repository
2.	ELK Stack 5.6.16 + Exporter doc type = “doc”
Test passed. WLS logs pushed to Elasticsearch repository
3.	ELK Stack 6.8.0 + + Exporter doc type = “_doc”
Test passed. WLS logs pushed to Elasticsearch repository
4.	ELK Stack 6.8.0 + Exporter doc type = “doc”
Test passed. WLS logs pushed to Elasticsearch repository


Please let me know if you'd to take a look at the Kibana console. I can save it again for you

**Comment by markxnelson** [comment]
Thanks. Let me test then I will review/approve

**Comment by hzhao-github** [comment]
Mark, do you want to borrow my scripts and partially automated source code to save you time?

**Comment by markxnelson** [comment]
Sure, thanks

**Comment by hzhao-github** [comment]
I am moving all changes to a newly-refreshed branch. let em make it work in my local and then push the changes

**Comment by hzhao-github** [comment]
forgot one more verification

to Verify:

    1)  check the index name "wls" exists in the server pods
    2)  Issue some Elasticsearch RESTful API calls to make sure wls logs are pushed to Elasticsearch repository
    3)  Launch Kibana Console, verify that index name "wls" and WLS logs are showing up
    4)  On "Discovery" panel, check that "type" embedded in WLS logs is "doc"

**Comment by markxnelson** [comment]
Thanks, I have verified this change against 5.6.16 and 6.8.0 and it looks good.

**Pull request merged**
